---
name: Build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - id: dockerbuild
        name: Build Multiarch Containers
        run: docker buildx build --platform=linux/amd64,linux/arm64 -t quay.io/scottharwell/m1-awx-operator-runner
